### ISSUE TITLE
Add information to signed in wallet screen

### ISSUE THREAD

**Issue by Jenm-b** [Greenstand/trings-ios#10]
**Story**
**As a** signed in Greenstand customer
**I want to** see the number of tokens etc
**so that** I have a better understanding of my wallet information

**Tasks**
- [ ] Show number of X to green label 
- [ ] Show number of X to yellow label 
- [ ] Show other useful information
